extent.reporter.spark.start=true
extent.reporter.spark.out=target/reports/extent/HtmlReport/ExtentHtml.html
screenshot.dir=target/reports/screenshots/
#screenshot.on.failure=true
screenshot.rel.path=../screenshots/
#extent.reporter.spark.base64imagesrc=true
